name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install package
      run: pip install sigmoidpythonpackage    

    - name: Install bump2version and patch
      run: pip install bump2version patch 

    # - name: Static Code Analysis
    #   run: |
    #     pip install bandit
    #     bandit -r .

    # - name: Dependency Scanning
    #   run: |
    #     pip install safety
    #     safety check
          
    - name: docker build
      run: docker build --build-arg GIT_SHA=${{ github.sha }} -t pypackage-pipeline:${{ github.sha }} -f ./linux/Dockerfile .

    - name: docker login
      run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'

    - name: tag docker image
      run: docker tag pypackage-pipeline:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/pypackage-pipeline:${{ github.sha }}

    - name: push docker image
      run: docker push '${{secrets.DOCKER_USERNAME}}'/pypackage-pipeline:'${{github.sha}}'

    # - name: Container Image Scanning
    #   run: trivy pypackage-pipeline:${{ github.sha }}
