name: CI for Python Package and deployment to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Update setuptools
      run: pip install --upgrade setuptools    

    - name: Install package
      run: pip install sigmoidpythonpackage 
      
    # - name: Static Code Analysis with pylint
    #   run: |
    #     pip install pylint
    #     pylint src/

    - name: Security Scanning with Bandit
      run: |
        pip install bandit
        bandit -r .

    - name: Dependency Scanning with Safety
      run: |
        pip install safety
        safety check

    - name: GitLeaks Scan
      run: |
        wget -O gitleaks https://github.com/zricethezav/gitleaks/releases/download/v7.0.0/gitleaks-linux-amd64
        chmod +x gitleaks
        ./gitleaks    
          
    - name: docker build
      run: docker build --build-arg GIT_SHA=${{ github.sha }} -t pypackage-pipeline:${{ github.sha }} -f ./linux/Dockerfile .

    - name: docker login
      run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'

    - name: tag docker image
      run: docker tag pypackage-pipeline:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/pypackage-pipeline:${{ github.sha }}

    - name: push docker image
      run: docker push '${{secrets.DOCKER_USERNAME}}'/pypackage-pipeline:'${{github.sha}}'

    - name: Install trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.19.1/trivy_0.19.1_Linux-64bit.deb -O trivy.deb
        sudo dpkg -i trivy.deb  

    - name: Container Image Scanning
      run: trivy pypackage-pipeline:${{ github.sha }}
