name: Python package installation for macOS

on:
  push:
    branches:
      - develop

jobs:
  run:
    runs-on: macOS-latest
    
    steps:
    - name: Install package
      run: pip install sigmoidpythonpackage    

   
