name: Python package installation for macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run:

    runs-on: macOS-latest

    steps:

    - name: Install package
      run: pip install sigmoidpythonlib    

   
