#!/usr/bin/env python
import sys
import re

# Get the commit message
commit_msg_file = sys.argv[1]
with open(commit_msg_file) as f:
    commit_msg = f.read()

# Define regular expressions to identify keywords in the commit message
major_pattern = re.compile(r'\[major\]', re.IGNORECASE)
minor_pattern = re.compile(r'\[minor\]', re.IGNORECASE)
patch_pattern = re.compile(r'\[patch\]', re.IGNORECASE)

# Determine the version bump based on the commit message
if major_pattern.search(commit_msg):
    version_bump = 'major'
elif minor_pattern.search(commit_msg):
    version_bump = 'minor'
elif patch_pattern.search(commit_msg):
    version_bump = 'patch'
else:
    version_bump = 'patch'  # Default to patch if no keyword is found

print(f'{version_bump}: ')
