name: Python Package

on:
  push:
    branches:
      - feature   


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install wheel 

      - name: Github Bumpversion Action
        uses: jaumann/github-bumpversion-action@v0.0.6  
        with:
          files: setup.py, .bumpversion.cfg
          part: minor 
          commit_name: rishabhvermarv99
          commit_email: rishabhverma3012.rv@gmail.com
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Package
        run: python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}   
      
