name: Python package installation for windows

on:
  workflow_dispatch: {}

jobs:

  run:

    runs-on: windows-latest

    steps:

    - name: Install package
      run: pip install sigmoidpythonpackage    
